get-content ENV | foreach {
  $name, $value = $_.split('=')
  set-content env:\$name $value
}

$molpro_root='molpro-teach-' + $env:molpro_version + '.windows_x64'
$molpro_zip=${molpro_root} + '.exe'
if (-not(Test-Path -path $molpro_zip)) {
  $full_url = $env:MOLPRO_TEACH_URL + '/' + $molpro_zip
  curl -O $full_url
}
7z -o"${molpro_root}" -aoa x -- ${molpro_zip}


cmd.exe /c conda install -c conda-forge -y --file=requirements.txt m2-base nsis pip
python -m pip install --no-build-isolation --no-deps .

$versionfile = ( $env:TMP, "\VERSION") -join ""
$PWD = (Get-Item .).FullName
git config --global --add safe.directory "$PWD"
$version = $( git describe --tags --dirty --always )
echo "$version" > "$versionfile"



If (Test-Path -path dist)
{
    rm dist -r -fo
}
$cp = $env:CONDA_PREFIX
$entry_script = Join-Path $env:TEMP "_pyinstaller_entry.py"
@"
# Generated by build.ps1. This is deliberately NOT written into the repo
# root: PyInstaller always adds the entry-point script's own directory to
# sys.path ahead of any --paths additions, and the repo root contains the
# real top-level iMolpro.py launcher. Leaving this file there would poison
# PyInstaller's own 'import iMolpro' resolution during analysis -- it would
# find that flat iMolpro.py first (a plain module, not a package) and never
# reach the real 'iMolpro' package under src/.
#
# Separately, this script must not share a name with a package it imports,
# or the package gets silently dropped from the bundle. --name iMolpro
# keeps the built .exe itself named iMolpro.
from iMolpro.__main__ import main

if __name__ == '__main__':
    main()
"@ | Out-File -Encoding utf8 $entry_script

pyinstaller --noconfirm `
  --name iMolpro `
  --paths="$PWD\src" `
  --collect-submodules=iMolpro `
  --add-data=src/iMolpro/data/Molpro_Logo_Molpro_Quantum_Chemistry_Software.png:. `
        --add-data=src/iMolpro/data/README.md:. `
          --add-data=src/iMolpro/data/doc:.\doc `
            --add-data="$versionfile":. `
            --add-data ${molpro_root}:.\molpro `
            --add-data=$cp\Library\usr\bin\nohup.exe:. `
            --add-data=$cp\Library\usr\bin\bash.exe:. `
            --add-data=$cp\Library\usr\bin\mkdir.exe:. `
            --add-data=$cp\Library\usr\bin\dirname.exe:. `
            --add-data=$cp\Library\usr\bin\ps.exe:. `
            --add-data=$cp\Library\rsync:.\rsync `
            --add-data=$cp\Lib\site-packages\pymolpro:.\pymolpro `
            --paths=$cp\Lib\site-packages `
              $pyinstaller_opt $entry_script
Remove-Item $entry_script

sed -i -e "s/hiddenimports=\[\]/hiddenimports=['scipy._cyutility', 'scipy.sparse._csparsetools', 'scipy._lib.messagestream']/" iMolpro.spec

$descriptor = ($version, 'Windows', $( uname -m )) -join "."
echo descriptor $descriptor
& $cp\NSIS\makensis.exe iMolpro.nsi
If (Test-Path -path iMolpro-$descriptor.exe)
{
    rm iMolpro-$descriptor.exe
}
Rename-item iMolpro.exe iMolpro-$descriptor.exe
