#!/bin/sh

#pkgbuild=1
dmg=1
#tar=1
sh=1

if [ -z "$NOCONDA" ]; then
#conda install -c conda-forge -c defaults -y --file=requirements.txt python=3.12 scipy=1.11  || exit 1
#conda remove -y pubchempy
#pip install -I https://github.com/molpro/PubChemPy/archive/refs/heads/main.zip
# iMolpro's own runtime dependencies live in exactly one place, pyproject.toml;
# this regenerates the conda-syntax file from it rather than maintaining a
# second, hand-edited copy that can silently drift out of sync.
conda_requirements=${TMPDIR:-/tmp}/imolpro-conda-requirements.txt
python3 scripts/generate_conda_requirements.py "$conda_requirements" || exit
conda install -q -c conda-forge -c defaults -y --file="$conda_requirements" --file=conda-build-tools.txt 'setuptools=80.9' pandoc pip || exit
python -m pip install --no-build-isolation --no-deps . || exit
gem install --user-install -n~/bin fpm
PATH=~/bin:$PATH
conda list
fi

#if [ "$(uname)" = Darwin -a $(uname -m) = x86_64 ]; then
#  conda install -c conda-forge -y scipy==1.11
#fi

. ./ENV

if [ "$(uname)" = Darwin ]; then
  application_signing_identity="Developer ID Application: Peter Knowles (LMLY9RHMA3)"
  pyinstaller_opt="--windowed --osx-bundle-identifier=net.molpro.iMolpro --icon=molpro.icns"
fi
builddir=${TMPDIR:-/tmp}/iMolpro
rm -rf "${builddir}"

versionfile=${TMPDIR:-/tmp}/VERSION
git config --global --add safe.directory "$PWD"
version=$(git describe --tags --dirty --always)
echo "$version" > "${versionfile}"

echo molpro_version=$molpro_version
molpro_script_gz=molpro-teach-$molpro_version.$(uname|tr '[:upper:]' '[:lower:]')_$(uname -m|sed -e 's/arm64/aarch64/').sh.gz
echo molpro_script_gz=$molpro_script_gz
if [ ! -r $molpro_script_gz ]; then
  wget -q ${MOLPRO_TEACH_URL}/$molpro_script_gz || echo WARNING molpro-teach not available
fi
if [ -r $molpro_script_gz ]; then
  gunzip -k -f $molpro_script_gz
  molpro_script=$(basename $molpro_script_gz .gz)
  sh $molpro_script -batch -prefix $builddir/molpro
  ls -lR $builddir/molpro/bin
  rm $molpro_script
  sed -i -e 's@MOLPRO_PREFIX=.*$@me=$(realpath $0 2>/dev/null) || me=$0; MOLPRO_PREFIX=$(dirname $(dirname $me))@' $builddir/molpro/bin/molpro
else
  mkdir -p $builddir/molpro
fi


rm -f iMolpro.spec
entry_script="${builddir}/_pyinstaller_entry.py"
mkdir -p "${builddir}"
cat > "${entry_script}" << 'PYEOF'
# Generated by build.sh. This is deliberately NOT written into the repo
# root: PyInstaller always adds the entry-point script's own directory to
# sys.path ahead of any --paths additions, and the repo root contains the
# real top-level iMolpro.py launcher. Leaving this file there would poison
# PyInstaller's own 'import iMolpro' resolution during analysis -- it would
# find that flat iMolpro.py first (a plain module, not a package) and never
# reach the real 'iMolpro' package under src/.
#
# Separately, this script must not share a name with a package it imports,
# or the package gets silently dropped from the bundle (PyInstaller indexes
# bundled modules by name, and an 'iMolpro' entry-point script collides with
# the 'iMolpro' package). --name iMolpro keeps the built executable/app
# itself named iMolpro as before.
from iMolpro.__main__ import main

if __name__ == '__main__':
    main()
PYEOF
PATH=/usr/bin:$PATH pyi-makespec \
  --name iMolpro \
  --paths="$PWD/src" \
  --collect-submodules=iMolpro \
  --add-data src/iMolpro/data/Molpro_Logo_Molpro_Quantum_Chemistry_Software.png:. \
  --add-data src/iMolpro/data/README.md:. \
  --add-data src/iMolpro/data/doc:./doc \
  --add-data "${versionfile}":. \
  --add-data $builddir/molpro:./molpro \
  --add-data $CONDA_PREFIX/lib/python$(python --version|sed -e 's/.* //' -e 's/\.[0-9]*$//')/site-packages/pymolpro/molpro_input.json:./pymolpro \
  $pyinstaller_opt \
  "${entry_script}" || exit 1
sed -i -e '$d' iMolpro.spec
sed -i -e "s/hiddenimports=\[/hiddenimports=['vtk', 'vtkmodules','vtkmodules.all','vtkmodules.qt','vtkmodules.qt.QVTKRenderWindowInteractor','vtkmodules.vtkRenderingCore','vtkmodules.vtkRenderingUI','vtkmodules.util','vtkmodules.util.numpy_support','vtkmodules.numpy_interface', 'vtkmodules.numpy_interface.dataset_adapter', 'scipy._cyutility', 'scipy.sparse._csparsetools', 'scipy._lib.messagestream', /" iMolpro.spec
cat << 'EOF' >> iMolpro.spec
    info_plist={
      'NSPrincipalClass' : 'NSApplication',
      'NSHighResolutionCapable' : 'True',
      'CFBundleDocumentTypes': [
        {
          'CFBundleTypeExtensions': ['molpro'],
          'LSTypeIsPackage': True,
          'CFBundleTypeIconFile': 'molpro.icns',
          'CFBundleTypeRole': 'Editor',
          'CFBundleTypeName': 'Molpro Project'
        },
        {
          'CFBundleTypeExtensions': ['inp'],
          'LSTypeIsPackage': False,
          'CFBundleTypeIconFile': 'molpro.icns',
          'CFBundleTypeRole': 'Viewer',
          'CFBundleTypeName': 'Molpro Input'
        },
        {
          'CFBundleTypeExtensions': ['out'],
          'LSTypeIsPackage': False,
          'CFBundleTypeIconFile': 'molpro.icns',
          'CFBundleTypeRole': 'Viewer',
          'CFBundleTypeName': 'Molpro Output'
        }
      ]
    }
)
EOF
PATH=/usr/bin:$PATH pyinstaller \
  --distpath "${builddir}"/dist \
  iMolpro.spec || exit 1
rm -f "${entry_script}"

if [ -d "${builddir}/dist/iMolpro/_internal/PySide6/Qt/lib" ]; then
  # Older PySide6 packaging nests libexec/resources/translations under Qt/lib;
  # newer builds ship them directly under Qt/ and need no symlinking at all.
  (cd ${builddir}/dist/iMolpro/_internal/PySide6/Qt/lib && ln -sf ../resources  .)
  (cd ${builddir}/dist/iMolpro/_internal/PySide6/Qt && ln -sf ./lib/qt6 ./libexec)
  (cd ${builddir}/dist/iMolpro/_internal/PySide6/Qt/lib && ln -sf ../translations .)
fi

descriptor=${version}.$(uname).$(uname -m)
if [ "$(uname)" = Darwin ]; then
if [ -d "${builddir}/dist/iMolpro.app/Contents/Frameworks/PySide6/Qt/lib" ]; then
  (cd ${builddir}/dist/iMolpro.app/Contents/Frameworks/PySide6/Qt/lib && ln -sf ../../../../Resources/PySide6/Qt/resources .&& ln -sf ../../../../Resources/PySide6/Qt/translations .)
  (cd ${builddir}/dist/iMolpro.app/Contents/Frameworks/PySide6/Qt && ln -sf ../../../Resources/PySide6/Qt/lib/qt6 ./libexec)
fi
#  (cd "${builddir}"/dist/iMolpro.app/Contents/Resources||exit 1; for i in PyQt5/Qt/resources/* ; do ln -s "$i" . ; done)
#  (cd "${builddir}"/dist/iMolpro.app/Contents||exit 1; ln -s MacOS/Resources/PyQt5/Qt/translations .)
#  find dist/iMolpro.app -type l ! -exec test -e {} \; -exec rm {} \;
  codesign -s "$application_signing_identity" --deep --force --options runtime "${builddir}"/dist/iMolpro.app
  codesign -s "$application_signing_identity" --force --options runtime "${builddir}"/dist/iMolpro.app

  codesign -dv "${builddir}"/dist/iMolpro.app

  rm -rf "${builddir}"/dist/iMolpro
#  cp -p doc/INSTALL_macOS_binary.md "${builddir}"/dist/INSTALL
  pandoc -f markdown -s Package-license.md -o "${builddir}"/dist/LICENSE.rtf
#  cp -p Package-license.md "${builddir}"/dist/
  (cd "${builddir}"/dist||exit 1; ln -s /Applications .)
  rm -f iMolpro-"${descriptor}".dmg
  if [ -r /Volumes/iMolpro-"${descriptor}" ]; then umount /Volumes/iMolpro-"${descriptor}" ; fi
  rm -rf dist
  mkdir -p dist
  ls -lR dist

  if [ ! -z "$pkgbuild" ]; then
    pip install macos_pkg_builder
    python <<EOF
from macos_pkg_builder import Packages
def contents(file):
    with open(file,'r') as f:
       return f.read()

pkg_obj = Packages(
    pkg_output="dist/iMolpro-${descriptor}.pkg",
    pkg_bundle_id="net.molpro.iMolpro",
    # pkg_preinstall_script="Samples/MyApp/MyPreinstall.sh",
    # pkg_postinstall_script="Samples/MyApp/MyPostinstall.sh",
    pkg_file_structure={
        "${builddir}/dist/iMolpro.app": "/Applications/iMolpro.app",
    },
    pkg_as_distribution=True,
    pkg_welcome=contents('Package-README.md'),
#    pkg_readme=contents('Package-README.md'),
    pkg_license=contents('Package-License.md'),
    pkg_title="iMolpro",
    # pkg_background="Molpro_Logo_Molpro_Quantum_Chemistry_Software.png",
    pkg_signing_identity="Developer ID Installer: Peter Knowles (LMLY9RHMA3)",
)

assert pkg_obj.build() is True
EOF
  fi

  if [ ! -z "$dmg" ]; then
#  create-dmg --app-drop-link 25 35 --volname iMolpro-"${descriptor}"  --volicon 'Molpro_Logo_Molpro_Quantum_Chemistry_Software.png' dist/iMolpro-"${descriptor}".dmg "${builddir}"/dist
  hdiutil create ./iMolpro.dmg -ov -fs HFS+ -srcfolder "${builddir}"/dist -volname iMolpro-"${descriptor}"
  echo after first hdiutil
  hdiutil convert ./iMolpro.dmg -format UDZO -o dist/iMolpro-"${descriptor}".dmg
  cp src/iMolpro/data/Molpro_Logo_Molpro_Quantum_Chemistry_Software.png "${builddir}"
  (cd "${builddir}" && sips -i Molpro_Logo_Molpro_Quantum_Chemistry_Software.png && DeRez -only icns Molpro_Logo_Molpro_Quantum_Chemistry_Software.png > tmp.rsrc)
  Rez -append "${builddir}"/tmp.rsrc -o dist/iMolpro-"${descriptor}".dmg
  SetFile -a C dist/iMolpro-"${descriptor}".dmg
  rm ./iMolpro.dmg
  fi
else
  rm -rf dist build
  mv "${builddir}"/dist .
  mkdir -p ./dist/iMolpro/_internal/pymolpro
  cp -p $CONDA_PREFIX/lib/python$(python --version|sed -e 's/.* //' -e 's/\.[0-9]*$//')/site-packages/pymolpro/molpro_input.json ./dist/iMolpro/_internal/pymolpro
  for l in libcrypto.so.3 libssl.so.3 ; do
    cp -p $(find ${CONDA_PREFIX} -name $l) $(find dist/iMolpro/_internal -name $l) # because, somehow, pyinstaller picks up the system libcrypto
  done
  # Opposite direction from the swap above: PyInstaller bundles conda's own
  # libpcre2-8.so.0, which lacks the glibc symbol-versioning info the
  # system's build expects. Subprocesses spawned at runtime (grep, sed, id,
  # ...) inherit LD_LIBRARY_PATH pointing at _internal and pick up that
  # version-info-less copy instead of the system's, producing spurious "no
  # version information available" warnings. Copying in the *build
  # machine's* own libpcre2 doesn't fix this for the .rpm output -- this
  # builds on Ubuntu but the .rpm installs on Fedora/RHEL-family systems,
  # so "the build machine's system copy" is a different distro's library
  # entirely and can just as easily mismatch the *installed* system's
  # libselinux/grep/sed. Simplest correct fix: don't bundle a copy at all,
  # so LD_LIBRARY_PATH's search falls through to whatever the actual
  # target machine already has -- essentially guaranteed present, since
  # grep/sed/systemd themselves depend on it.
  find dist/iMolpro/_internal -name 'libpcre2-8.so*' -print -delete
  if [ ! -z "$tar" ]; then
  tar cjf dist/iMolpro-"${descriptor}".tar.bz2 -C dist iMolpro
  fi
  if [ ! -z "$sh" ]; then
    prefix='/usr'
    echo '#!/bin/sh' > ${builddir}/postinstall
    echo "ln -sf ${prefix}/libexec/iMolpro/iMolpro ${prefix}/bin/iMolpro" >> ${builddir}/postinstall
    echo '#!/bin/sh' > ${builddir}/postremove
    echo "rm -rf ${prefix}/libexec/iMolpro ${prefix}/bin/iMolpro" >> ${builddir}/postremove
    echo version=$version
    if [[ $version =~ ^[0-9]*\.[0-9]*\.[0-9]*$ ]] ; then true ; else version="0.0.0" ; fi
    echo version=$version
    for type in deb rpm ; do
      rm -f dist/iMolpro-"${descriptor}".${type}
      dash='-'; if [ $type = rpm ]; then dash='_'; fi
      fpm -s dir -C dist -t ${type} -p dist/imolpro-"${descriptor}".${type} -v "${version}" -n imolpro --prefix=${prefix}/libexec --after-install ${builddir}/postinstall --after-remove ${builddir}/postremove --license LGPLv3 --description "$(cat Package-README.md)" --provides iMolpro --url https://github.com/molpro/iMolpro --vendor molpro -f iMolpro
    done
  fi
fi
