permissions:
  contents: write
name: Deploy
on:
  push:
    #tags:
      #- '*'

jobs:
  deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, [macOS, ARM64]]
        os: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: s-weigand/setup-conda@v1
        if: ${{ matrix.os == 'ubuntu-latest' }}
      #- run: brew install miniconda
        #if: ${{ matrix.os == 'macos-latest' }}
      - name: Build
        run: |
          if [ -z "${CONDA_EXE}" ]; then export CONDA_EXE=$(readlink -f $(which conda)) ; fi
          git fetch --tags
          conda config --set solver libmamba
          . $(dirname $CONDA_EXE)/../etc/profile.d/conda.sh
          conda create -n QtMolpro-github
          conda activate QtMolpro-github
          bash build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*bz2
            dist/*dmg
